# Generated by Django 4.2.10 on 2024-02-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_rename_receipe_description_receipe_receipe_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='reciepe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
