# Generated by Django 4.2.10 on 2024-02-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_department_studentid_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentid',
            old_name='Student_id',
            new_name='student_id',
        ),
    ]
