# Generated by Django 4.2.10 on 2024-02-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_rankstudnet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rankstudnet',
            unique_together={('student_rank', 'student_rank_generation_date')},
        ),
    ]
