# Generated by Django 4.2.10 on 2024-02-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0011_student_student_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_rank',
        ),
    ]
