# Generated by Django 4.2.10 on 2024-02-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0014_remove_receipe_is_deleted_student_is_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rankstudnet',
            unique_together=set(),
        ),
    ]
