# Generated by Django 4.2.10 on 2024-02-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0016_alter_rankstudnet_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rankstudnet',
            unique_together=set(),
        ),
    ]
