# Generated by Django 4.2.10 on 2024-02-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0020_alter_rankstudnet_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankstudnet',
            name='number',
            field=models.IntegerField(default=10),
        ),
    ]
